Repository hhm970/c10-games-tracker-project, pull requests merged in 2024-04, with the labels that each got.

#66 Update main.yml
  .github/workflows/main.yml
  pipeline/test_fake.py
Labels: bug

#73 new diagram
  diagrams/ERD diagram.png
Labels: bug, documentation

#70 Create steam extract
  pipeline/requirements.txt
  pipeline/steam_extract.py
Labels: enhancement
